### ISSUE TITLE
`isLeft` causes compilation error on GHC 7.6.3

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#23]
`isLeft` and other related functions are newly introduced to `Data.Either`, which should not be used if we want our compiler to work on GHC 7.6.3.
